### ISSUE TITLE
idex status "Internal server error"

### ISSUE THREAD

**Issue by fab-io** [idexio/IDEXd#7]
Today I am getting this error:

```
aurad@aurad:~$ idex status
idexd-cli v0.2.1
Latest version: v0.2.1
Cold wallet: 0x....
StatusCodeError: 500 - {"message":"Internal server error"}
    at new StatusCodeError (~/.nvm/versions/node/v10.15.0/lib/node_modules/@idexio/idexd-cli/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (~/.nvm/versions/node/v10.15.0/lib/node_modules/@idexio/idexd-cli/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (~/.nvm/versions/node/v10.15.0/lib/node_modules/@idexio/idexd-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (~/.nvm/versions/node/v10.15.0/lib/node_modules/@idexio/idexd-cli/node_modules/request/request.js:185:22)
    at Request.<anonymous> (~/.nvm/versions/node/v10.15.0/lib/node_modules/@idexio/idexd-cli/node_modules/request/request.js:1161:10)
    at IncomingMessage.<anonymous> (~/.nvm/versions/node/v10.15.0/lib/node_modules/@idexio/idexd-cli/node_modules/request/request.js:1083:12)
```

**Comment by dahifi** [comment]
Would recommend asking for help in Discord. They seem to be responsive in there.
